USE DATABASE CCI_INTELLIGENCE;
USE SCHEMA RAW;

CREATE OR REPLACE CORTEX SEARCH SERVICE CCI_KNOWLEDGE_SEARCH
  ON CONTENT
  ATTRIBUTES CATEGORY, SUBCATEGORY, KEYWORDS
  WAREHOUSE = CCI_WH
  TARGET_LAG = '1 hour'
  COMMENT = 'Cortex Search service for Consumer Cellular knowledge base articles'
AS (
  SELECT 
    ARTICLE_ID,
    TITLE,
    CATEGORY,
    SUBCATEGORY,
    CONTENT,
    KEYWORDS,
    LAST_UPDATED
  FROM CCI_INTELLIGENCE.RAW.KNOWLEDGE_BASE
);
