USE DATABASE CCI_INTELLIGENCE;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    AGE NUMBER,
    SIGNUP_DATE DATE,
    CUSTOMER_SEGMENT VARCHAR(50),
    PREFERRED_CONTACT_METHOD VARCHAR(50),
    AARP_MEMBER BOOLEAN,
    REFERRAL_SOURCE VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PLANS (
    PLAN_ID VARCHAR(20) PRIMARY KEY,
    PLAN_NAME VARCHAR(100),
    PLAN_TYPE VARCHAR(50),
    MONTHLY_PRICE NUMBER(10,2),
    DATA_LIMIT_GB NUMBER,
    TALK_MINUTES NUMBER,
    TEXT_LIMIT NUMBER,
    UNLIMITED_DATA BOOLEAN,
    UNLIMITED_TALK BOOLEAN,
    UNLIMITED_TEXT BOOLEAN,
    NETWORK_CARRIER VARCHAR(50),
    FEATURES VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SUBSCRIPTIONS (
    SUBSCRIPTION_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    PLAN_ID VARCHAR(20) REFERENCES PLANS(PLAN_ID),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR(20),
    AUTO_PAY_ENABLED BOOLEAN,
    PAYMENT_METHOD VARCHAR(50),
    MONTHLY_BILL NUMBER(10,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DEVICES (
    DEVICE_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    DEVICE_BRAND VARCHAR(100),
    DEVICE_MODEL VARCHAR(200),
    DEVICE_TYPE VARCHAR(50),
    IMEI VARCHAR(20),
    PURCHASE_DATE DATE,
    PURCHASE_TYPE VARCHAR(50),
    DEVICE_PRICE NUMBER(10,2),
    WARRANTY_END_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE USAGE_DATA (
    USAGE_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    SUBSCRIPTION_ID VARCHAR(20) REFERENCES SUBSCRIPTIONS(SUBSCRIPTION_ID),
    USAGE_DATE DATE,
    USAGE_MONTH VARCHAR(7),
    DATA_USED_GB NUMBER(10,3),
    TALK_MINUTES_USED NUMBER,
    TEXTS_SENT NUMBER,
    OVERAGE_CHARGES NUMBER(10,2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE BILLING (
    BILLING_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    SUBSCRIPTION_ID VARCHAR(20) REFERENCES SUBSCRIPTIONS(SUBSCRIPTION_ID),
    BILLING_DATE DATE,
    BILLING_PERIOD_START DATE,
    BILLING_PERIOD_END DATE,
    PLAN_CHARGE NUMBER(10,2),
    DEVICE_PAYMENT NUMBER(10,2),
    TAXES_FEES NUMBER(10,2),
    OVERAGE_CHARGES NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR(20),
    PAYMENT_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE SUPPORT_TICKETS (
    TICKET_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CREATED_DATE TIMESTAMP_NTZ,
    RESOLVED_DATE TIMESTAMP_NTZ,
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    PRIORITY VARCHAR(20),
    STATUS VARCHAR(20),
    CHANNEL VARCHAR(50),
    ISSUE_DESCRIPTION VARCHAR(2000),
    RESOLUTION_NOTES VARCHAR(2000),
    AGENT_ID VARCHAR(20),
    SATISFACTION_SCORE NUMBER(1),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KNOWLEDGE_BASE (
    ARTICLE_ID VARCHAR(20) PRIMARY KEY,
    TITLE VARCHAR(500),
    CATEGORY VARCHAR(100),
    SUBCATEGORY VARCHAR(100),
    CONTENT TEXT,
    KEYWORDS VARCHAR(500),
    LAST_UPDATED DATE,
    VIEW_COUNT NUMBER,
    HELPFUL_COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_FEEDBACK (
    FEEDBACK_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FEEDBACK_DATE DATE,
    FEEDBACK_TYPE VARCHAR(50),
    NPS_SCORE NUMBER(2),
    CSAT_SCORE NUMBER(1),
    COMMENTS VARCHAR(2000),
    FOLLOW_UP_REQUIRED BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CHURN_PREDICTIONS (
    PREDICTION_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    PREDICTION_DATE DATE,
    CHURN_PROBABILITY NUMBER(5,4),
    CHURN_RISK_LEVEL VARCHAR(20),
    KEY_RISK_FACTORS VARCHAR(1000),
    RECOMMENDED_ACTION VARCHAR(500),
    MODEL_VERSION VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CUSTOMER_LTV (
    LTV_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(20) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CALCULATION_DATE DATE,
    HISTORICAL_REVENUE NUMBER(12,2),
    PREDICTED_LIFETIME_VALUE NUMBER(12,2),
    TENURE_MONTHS NUMBER,
    AVG_MONTHLY_REVENUE NUMBER(10,2),
    LTV_SEGMENT VARCHAR(20),
    MODEL_VERSION VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
