USE DATABASE CCI_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW CUSTOMER_360 AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL,
    c.PHONE,
    c.AGE,
    c.CUSTOMER_SEGMENT,
    c.AARP_MEMBER,
    c.SIGNUP_DATE,
    DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) AS TENURE_MONTHS,
    s.PLAN_ID,
    p.PLAN_NAME,
    p.PLAN_TYPE,
    p.MONTHLY_PRICE AS PLAN_PRICE,
    s.STATUS AS SUBSCRIPTION_STATUS,
    s.AUTO_PAY_ENABLED,
    d.DEVICE_BRAND,
    d.DEVICE_MODEL,
    d.DEVICE_TYPE,
    ltv.PREDICTED_LIFETIME_VALUE,
    ltv.LTV_SEGMENT,
    ltv.AVG_MONTHLY_REVENUE,
    churn.CHURN_PROBABILITY,
    churn.CHURN_RISK_LEVEL,
    churn.KEY_RISK_FACTORS,
    churn.RECOMMENDED_ACTION
FROM CCI_INTELLIGENCE.RAW.CUSTOMERS c
LEFT JOIN CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.PLANS p ON s.PLAN_ID = p.PLAN_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.DEVICES d ON c.CUSTOMER_ID = d.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CUSTOMER_LTV ltv ON c.CUSTOMER_ID = ltv.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CHURN_PREDICTIONS churn ON c.CUSTOMER_ID = churn.CUSTOMER_ID;

CREATE OR REPLACE VIEW MONTHLY_REVENUE_SUMMARY AS
SELECT 
    DATE_TRUNC('MONTH', b.BILLING_DATE) AS BILLING_MONTH,
    COUNT(DISTINCT b.CUSTOMER_ID) AS ACTIVE_CUSTOMERS,
    SUM(b.PLAN_CHARGE) AS TOTAL_PLAN_REVENUE,
    SUM(b.DEVICE_PAYMENT) AS TOTAL_DEVICE_REVENUE,
    SUM(b.OVERAGE_CHARGES) AS TOTAL_OVERAGE_REVENUE,
    SUM(b.TAXES_FEES) AS TOTAL_TAXES_FEES,
    SUM(b.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(b.TOTAL_AMOUNT) AS AVG_REVENUE_PER_CUSTOMER,
    SUM(CASE WHEN b.PAYMENT_STATUS = 'Paid' THEN b.TOTAL_AMOUNT ELSE 0 END) AS COLLECTED_REVENUE,
    SUM(CASE WHEN b.PAYMENT_STATUS = 'Past Due' THEN b.TOTAL_AMOUNT ELSE 0 END) AS OUTSTANDING_REVENUE
FROM CCI_INTELLIGENCE.RAW.BILLING b
GROUP BY DATE_TRUNC('MONTH', b.BILLING_DATE)
ORDER BY BILLING_MONTH DESC;

CREATE OR REPLACE VIEW SUPPORT_ANALYTICS AS
SELECT 
    DATE_TRUNC('MONTH', t.CREATED_DATE) AS TICKET_MONTH,
    t.CATEGORY,
    t.PRIORITY,
    COUNT(*) AS TICKET_COUNT,
    SUM(CASE WHEN t.STATUS = 'Resolved' THEN 1 ELSE 0 END) AS RESOLVED_COUNT,
    ROUND(AVG(CASE WHEN t.RESOLVED_DATE IS NOT NULL 
        THEN DATEDIFF(HOUR, t.CREATED_DATE, t.RESOLVED_DATE) END), 2) AS AVG_RESOLUTION_HOURS,
    ROUND(AVG(t.SATISFACTION_SCORE), 2) AS AVG_CSAT
FROM CCI_INTELLIGENCE.RAW.SUPPORT_TICKETS t
GROUP BY DATE_TRUNC('MONTH', t.CREATED_DATE), t.CATEGORY, t.PRIORITY;

CREATE OR REPLACE VIEW USAGE_PATTERNS AS
SELECT 
    u.USAGE_MONTH,
    c.CUSTOMER_SEGMENT,
    p.PLAN_TYPE,
    COUNT(DISTINCT u.CUSTOMER_ID) AS CUSTOMER_COUNT,
    ROUND(AVG(u.DATA_USED_GB), 3) AS AVG_DATA_GB,
    ROUND(AVG(u.TALK_MINUTES_USED), 0) AS AVG_TALK_MINUTES,
    ROUND(AVG(u.TEXTS_SENT), 0) AS AVG_TEXTS,
    SUM(u.OVERAGE_CHARGES) AS TOTAL_OVERAGE
FROM CCI_INTELLIGENCE.RAW.USAGE_DATA u
JOIN CCI_INTELLIGENCE.RAW.CUSTOMERS c ON u.CUSTOMER_ID = c.CUSTOMER_ID
JOIN CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s ON u.SUBSCRIPTION_ID = s.SUBSCRIPTION_ID
JOIN CCI_INTELLIGENCE.RAW.PLANS p ON s.PLAN_ID = p.PLAN_ID
GROUP BY u.USAGE_MONTH, c.CUSTOMER_SEGMENT, p.PLAN_TYPE
ORDER BY u.USAGE_MONTH DESC;

CREATE OR REPLACE VIEW CHURN_RISK_DASHBOARD AS
SELECT 
    churn.CHURN_RISK_LEVEL,
    c.CUSTOMER_SEGMENT,
    COUNT(*) AS CUSTOMER_COUNT,
    ROUND(AVG(churn.CHURN_PROBABILITY), 4) AS AVG_CHURN_PROBABILITY,
    ROUND(AVG(ltv.PREDICTED_LIFETIME_VALUE), 2) AS AVG_LTV_AT_RISK,
    SUM(ltv.PREDICTED_LIFETIME_VALUE) AS TOTAL_LTV_AT_RISK
FROM CCI_INTELLIGENCE.RAW.CHURN_PREDICTIONS churn
JOIN CCI_INTELLIGENCE.RAW.CUSTOMERS c ON churn.CUSTOMER_ID = c.CUSTOMER_ID
JOIN CCI_INTELLIGENCE.RAW.CUSTOMER_LTV ltv ON churn.CUSTOMER_ID = ltv.CUSTOMER_ID
GROUP BY churn.CHURN_RISK_LEVEL, c.CUSTOMER_SEGMENT
ORDER BY churn.CHURN_RISK_LEVEL, c.CUSTOMER_SEGMENT;

CREATE OR REPLACE VIEW PLAN_PERFORMANCE AS
SELECT 
    p.PLAN_ID,
    p.PLAN_NAME,
    p.PLAN_TYPE,
    p.MONTHLY_PRICE,
    COUNT(DISTINCT s.CUSTOMER_ID) AS SUBSCRIBER_COUNT,
    SUM(CASE WHEN s.STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_SUBSCRIBERS,
    SUM(CASE WHEN s.STATUS = 'Cancelled' THEN 1 ELSE 0 END) AS CHURNED_SUBSCRIBERS,
    ROUND(SUM(CASE WHEN s.STATUS = 'Cancelled' THEN 1 ELSE 0 END)::FLOAT / 
          NULLIF(COUNT(DISTINCT s.CUSTOMER_ID), 0) * 100, 2) AS CHURN_RATE_PCT,
    SUM(b.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CCI_INTELLIGENCE.RAW.PLANS p
LEFT JOIN CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s ON p.PLAN_ID = s.PLAN_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.BILLING b ON s.SUBSCRIPTION_ID = b.SUBSCRIPTION_ID
GROUP BY p.PLAN_ID, p.PLAN_NAME, p.PLAN_TYPE, p.MONTHLY_PRICE
ORDER BY SUBSCRIBER_COUNT DESC;

CREATE OR REPLACE VIEW CUSTOMER_HEALTH_SCORE AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    ROUND(
        (CASE 
            WHEN ltv.LTV_SEGMENT = 'Platinum' THEN 25
            WHEN ltv.LTV_SEGMENT = 'Gold' THEN 20
            WHEN ltv.LTV_SEGMENT = 'Silver' THEN 15
            ELSE 10
        END) +
        (CASE 
            WHEN churn.CHURN_RISK_LEVEL = 'Low' THEN 25
            WHEN churn.CHURN_RISK_LEVEL = 'Medium' THEN 15
            ELSE 5
        END) +
        (CASE WHEN s.AUTO_PAY_ENABLED THEN 15 ELSE 5 END) +
        (CASE 
            WHEN DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) > 24 THEN 20
            WHEN DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) > 12 THEN 15
            ELSE 10
        END) +
        (COALESCE((SELECT AVG(SATISFACTION_SCORE) * 3 FROM CCI_INTELLIGENCE.RAW.SUPPORT_TICKETS WHERE CUSTOMER_ID = c.CUSTOMER_ID), 10))
    , 0) AS HEALTH_SCORE,
    ltv.LTV_SEGMENT,
    churn.CHURN_RISK_LEVEL,
    DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) AS TENURE_MONTHS
FROM CCI_INTELLIGENCE.RAW.CUSTOMERS c
LEFT JOIN CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CUSTOMER_LTV ltv ON c.CUSTOMER_ID = ltv.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CHURN_PREDICTIONS churn ON c.CUSTOMER_ID = churn.CUSTOMER_ID;
