USE DATABASE CCI_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE CORTEX SEARCH SERVICE CCI_KNOWLEDGE_SEARCH
  ON CONTENT
  ATTRIBUTES TITLE, CATEGORY, SUBCATEGORY, KEYWORDS
  WAREHOUSE = CCI_WH
  TARGET_LAG = '1 day'
  COMMENT = 'Knowledge base search for Consumer Cellular support articles'
AS (
  SELECT 
    ARTICLE_ID,
    TITLE,
    CATEGORY,
    SUBCATEGORY,
    CONTENT,
    KEYWORDS,
    LAST_UPDATED
  FROM CCI_INTELLIGENCE.RAW.KNOWLEDGE_BASE
);

CREATE OR REPLACE CORTEX SEARCH SERVICE CCI_SUPPORT_TICKET_SEARCH
  ON ISSUE_DESCRIPTION
  ATTRIBUTES CATEGORY, SUBCATEGORY, PRIORITY, STATUS, RESOLUTION_NOTES
  WAREHOUSE = CCI_WH
  TARGET_LAG = '1 day'
  COMMENT = 'Support ticket search for finding similar past issues and resolutions'
AS (
  SELECT 
    TICKET_ID,
    CATEGORY,
    SUBCATEGORY,
    PRIORITY,
    STATUS,
    ISSUE_DESCRIPTION,
    RESOLUTION_NOTES,
    CREATED_DATE
  FROM CCI_INTELLIGENCE.RAW.SUPPORT_TICKETS
  WHERE RESOLUTION_NOTES IS NOT NULL
);

CREATE OR REPLACE CORTEX SEARCH SERVICE CCI_FEEDBACK_SEARCH
  ON COMMENTS
  ATTRIBUTES FEEDBACK_TYPE, NPS_SCORE, CSAT_SCORE
  WAREHOUSE = CCI_WH
  TARGET_LAG = '1 day'
  COMMENT = 'Customer feedback search for sentiment analysis and insights'
AS (
  SELECT 
    FEEDBACK_ID,
    CUSTOMER_ID,
    FEEDBACK_DATE,
    FEEDBACK_TYPE,
    NPS_SCORE,
    CSAT_SCORE,
    COMMENTS
  FROM CCI_INTELLIGENCE.RAW.CUSTOMER_FEEDBACK
  WHERE COMMENTS IS NOT NULL
);
