USE DATABASE CCI_INTELLIGENCE;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE FUNCTION GET_CUSTOMER_SUMMARY(CUST_ID VARCHAR)
RETURNS TABLE (
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    AGE NUMBER,
    SEGMENT VARCHAR,
    PLAN_NAME VARCHAR,
    STATUS VARCHAR,
    TENURE_MONTHS NUMBER,
    LTV_SEGMENT VARCHAR,
    CHURN_RISK VARCHAR,
    HEALTH_SCORE NUMBER
)
LANGUAGE SQL
AS
$$
SELECT 
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.EMAIL,
    c.PHONE,
    c.AGE,
    c.CUSTOMER_SEGMENT AS SEGMENT,
    p.PLAN_NAME,
    s.STATUS,
    DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) AS TENURE_MONTHS,
    ltv.LTV_SEGMENT,
    churn.CHURN_RISK_LEVEL AS CHURN_RISK,
    ROUND(
        (CASE WHEN ltv.LTV_SEGMENT = 'Platinum' THEN 25 WHEN ltv.LTV_SEGMENT = 'Gold' THEN 20 WHEN ltv.LTV_SEGMENT = 'Silver' THEN 15 ELSE 10 END) +
        (CASE WHEN churn.CHURN_RISK_LEVEL = 'Low' THEN 25 WHEN churn.CHURN_RISK_LEVEL = 'Medium' THEN 15 ELSE 5 END) +
        (CASE WHEN s.AUTO_PAY_ENABLED THEN 15 ELSE 5 END) +
        (CASE WHEN DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) > 24 THEN 20 WHEN DATEDIFF(MONTH, c.SIGNUP_DATE, CURRENT_DATE()) > 12 THEN 15 ELSE 10 END)
    , 0) AS HEALTH_SCORE
FROM CCI_INTELLIGENCE.RAW.CUSTOMERS c
LEFT JOIN CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s ON c.CUSTOMER_ID = s.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.PLANS p ON s.PLAN_ID = p.PLAN_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CUSTOMER_LTV ltv ON c.CUSTOMER_ID = ltv.CUSTOMER_ID
LEFT JOIN CCI_INTELLIGENCE.RAW.CHURN_PREDICTIONS churn ON c.CUSTOMER_ID = churn.CUSTOMER_ID
WHERE c.CUSTOMER_ID = CUST_ID
$$;

CREATE OR REPLACE FUNCTION GET_CUSTOMER_BILLING_HISTORY(CUST_ID VARCHAR)
RETURNS TABLE (
    BILLING_DATE DATE,
    PLAN_CHARGE NUMBER,
    DEVICE_PAYMENT NUMBER,
    OVERAGE_CHARGES NUMBER,
    TAXES_FEES NUMBER,
    TOTAL_AMOUNT NUMBER,
    PAYMENT_STATUS VARCHAR
)
LANGUAGE SQL
AS
$$
SELECT 
    BILLING_DATE,
    PLAN_CHARGE,
    DEVICE_PAYMENT,
    OVERAGE_CHARGES,
    TAXES_FEES,
    TOTAL_AMOUNT,
    PAYMENT_STATUS
FROM CCI_INTELLIGENCE.RAW.BILLING
WHERE CUSTOMER_ID = CUST_ID
ORDER BY BILLING_DATE DESC
LIMIT 12
$$;

CREATE OR REPLACE FUNCTION GET_CUSTOMER_SUPPORT_HISTORY(CUST_ID VARCHAR)
RETURNS TABLE (
    TICKET_ID VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ,
    CATEGORY VARCHAR,
    ISSUE VARCHAR,
    STATUS VARCHAR,
    RESOLUTION VARCHAR,
    SATISFACTION NUMBER
)
LANGUAGE SQL
AS
$$
SELECT 
    TICKET_ID,
    CREATED_DATE,
    CATEGORY,
    ISSUE_DESCRIPTION AS ISSUE,
    STATUS,
    RESOLUTION_NOTES AS RESOLUTION,
    SATISFACTION_SCORE AS SATISFACTION
FROM CCI_INTELLIGENCE.RAW.SUPPORT_TICKETS
WHERE CUSTOMER_ID = CUST_ID
ORDER BY CREATED_DATE DESC
LIMIT 10
$$;

CREATE OR REPLACE FUNCTION GET_CHURN_AT_RISK_CUSTOMERS(RISK_LEVEL VARCHAR, LIMIT_COUNT NUMBER)
RETURNS TABLE (
    CUSTOMER_ID VARCHAR,
    CUSTOMER_NAME VARCHAR,
    SEGMENT VARCHAR,
    CHURN_PROBABILITY NUMBER,
    KEY_RISK_FACTORS VARCHAR,
    RECOMMENDED_ACTION VARCHAR,
    LTV NUMBER
)
LANGUAGE SQL
AS
$$
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT AS SEGMENT,
    churn.CHURN_PROBABILITY,
    churn.KEY_RISK_FACTORS,
    churn.RECOMMENDED_ACTION,
    ltv.PREDICTED_LIFETIME_VALUE AS LTV
FROM CCI_INTELLIGENCE.RAW.CHURN_PREDICTIONS churn
JOIN CCI_INTELLIGENCE.RAW.CUSTOMERS c ON churn.CUSTOMER_ID = c.CUSTOMER_ID
JOIN CCI_INTELLIGENCE.RAW.CUSTOMER_LTV ltv ON churn.CUSTOMER_ID = ltv.CUSTOMER_ID
WHERE churn.CHURN_RISK_LEVEL = RISK_LEVEL
ORDER BY churn.CHURN_PROBABILITY DESC, ltv.PREDICTED_LIFETIME_VALUE DESC
LIMIT LIMIT_COUNT
$$;

CREATE OR REPLACE FUNCTION RECOMMEND_PLAN(CUST_ID VARCHAR)
RETURNS TABLE (
    CURRENT_PLAN VARCHAR,
    CURRENT_PRICE NUMBER,
    RECOMMENDED_PLAN VARCHAR,
    RECOMMENDED_PRICE NUMBER,
    REASON VARCHAR
)
LANGUAGE SQL
AS
$$
WITH customer_usage AS (
    SELECT 
        AVG(u.DATA_USED_GB) AS AVG_DATA,
        AVG(u.TALK_MINUTES_USED) AS AVG_TALK,
        AVG(u.TEXTS_SENT) AS AVG_TEXT,
        SUM(u.OVERAGE_CHARGES) AS TOTAL_OVERAGE
    FROM CCI_INTELLIGENCE.RAW.USAGE_DATA u
    WHERE u.CUSTOMER_ID = CUST_ID
),
current_plan AS (
    SELECT p.PLAN_NAME, p.MONTHLY_PRICE, p.DATA_LIMIT_GB, p.UNLIMITED_DATA
    FROM CCI_INTELLIGENCE.RAW.SUBSCRIPTIONS s
    JOIN CCI_INTELLIGENCE.RAW.PLANS p ON s.PLAN_ID = p.PLAN_ID
    WHERE s.CUSTOMER_ID = CUST_ID
    LIMIT 1
)
SELECT 
    cp.PLAN_NAME AS CURRENT_PLAN,
    cp.MONTHLY_PRICE AS CURRENT_PRICE,
    CASE 
        WHEN cu.AVG_DATA > 8 THEN 'Unlimited Premium'
        WHEN cu.AVG_DATA > 5 THEN 'Connect 10GB'
        WHEN cu.AVG_DATA > 3 THEN 'Connect 5GB'
        WHEN cu.AVG_DATA > 1 THEN 'Connect 3GB'
        ELSE 'Connect 1GB'
    END AS RECOMMENDED_PLAN,
    CASE 
        WHEN cu.AVG_DATA > 8 THEN 55.00
        WHEN cu.AVG_DATA > 5 THEN 35.00
        WHEN cu.AVG_DATA > 3 THEN 30.00
        WHEN cu.AVG_DATA > 1 THEN 25.00
        ELSE 20.00
    END AS RECOMMENDED_PRICE,
    CASE 
        WHEN cu.TOTAL_OVERAGE > 50 THEN 'High overage charges - upgrade would save money'
        WHEN cu.AVG_DATA > cp.DATA_LIMIT_GB AND NOT cp.UNLIMITED_DATA THEN 'Usage exceeds current plan limits'
        WHEN cu.AVG_DATA < cp.DATA_LIMIT_GB * 0.5 THEN 'Current usage below plan - consider downgrade'
        ELSE 'Current plan is well-suited for usage patterns'
    END AS REASON
FROM customer_usage cu
CROSS JOIN current_plan cp
$$;

CREATE OR REPLACE FUNCTION GET_REVENUE_METRICS(MONTHS_BACK NUMBER)
RETURNS TABLE (
    BILLING_MONTH DATE,
    TOTAL_REVENUE NUMBER,
    AVG_REVENUE_PER_CUSTOMER NUMBER,
    CUSTOMER_COUNT NUMBER,
    OVERAGE_REVENUE NUMBER,
    COLLECTION_RATE NUMBER
)
LANGUAGE SQL
AS
$$
SELECT 
    DATE_TRUNC('MONTH', BILLING_DATE)::DATE AS BILLING_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_REVENUE_PER_CUSTOMER,
    COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT,
    SUM(OVERAGE_CHARGES) AS OVERAGE_REVENUE,
    ROUND(SUM(CASE WHEN PAYMENT_STATUS = 'Paid' THEN TOTAL_AMOUNT ELSE 0 END) / NULLIF(SUM(TOTAL_AMOUNT), 0) * 100, 2) AS COLLECTION_RATE
FROM CCI_INTELLIGENCE.RAW.BILLING
WHERE BILLING_DATE >= DATEADD(MONTH, -MONTHS_BACK, CURRENT_DATE())
GROUP BY DATE_TRUNC('MONTH', BILLING_DATE)
ORDER BY BILLING_MONTH DESC
$$;

CREATE OR REPLACE FUNCTION SEARCH_KNOWLEDGE_BASE(SEARCH_QUERY VARCHAR)
RETURNS TABLE (
    ARTICLE_ID VARCHAR,
    TITLE VARCHAR,
    CATEGORY VARCHAR,
    CONTENT VARCHAR,
    RELEVANCE_HINT VARCHAR
)
LANGUAGE SQL
AS
$$
SELECT 
    ARTICLE_ID,
    TITLE,
    CATEGORY,
    CONTENT,
    'Keyword match' AS RELEVANCE_HINT
FROM CCI_INTELLIGENCE.RAW.KNOWLEDGE_BASE
WHERE 
    LOWER(TITLE) LIKE '%' || LOWER(SEARCH_QUERY) || '%'
    OR LOWER(CONTENT) LIKE '%' || LOWER(SEARCH_QUERY) || '%'
    OR LOWER(KEYWORDS) LIKE '%' || LOWER(SEARCH_QUERY) || '%'
ORDER BY VIEW_COUNT DESC
LIMIT 5
$$;
