CREATE DATABASE IF NOT EXISTS CCI_INTELLIGENCE;
USE DATABASE CCI_INTELLIGENCE;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE WAREHOUSE CCI_WH WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for Consumer Cellular Intelligence Agent';

USE WAREHOUSE CCI_WH;
